# Generated by Django 4.2.23 on 2025-10-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='restaurant_slug',
            field=models.CharField(default='rest1', max_length=50),
        ),
        migrations.AddField(
            model_name='table',
            name='table_number',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
