# Generated by Django 4.2.23 on 2025-10-26 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_table_restaurant_slug_table_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='billline',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billline',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
